# Generated by Django 4.1.4 on 2022-12-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_predmet_natjecanje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sudionik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sudionik_ime', models.CharField(max_length=25)),
                ('sudionik_prezime', models.CharField(max_length=50)),
                ('student_broj_xice', models.CharField(max_length=10)),
                ('student_natjecanja', models.ManyToManyField(to='main.natjecanje')),
            ],
        ),
    ]
