# Generated by Django 4.1.4 on 2022-12-21 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natjecanje',
            name='natjecanje_vrijeme',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
